---
server:
  port: 8080
  contextPath: /stateservice/v1

---
###
# Spring Security Configuration
###
#security:
# user:
#  name: admin
#  password: 
#  role: USER,SYSADMIN
  
 

# ===============================
# = SPRING / JPA / HIBERNATE
# =============================== 
 
spring:
  profiles: local, default
  datasource:
    url: jdbc:mysql://localhost:3306/ueatfit
    username: root
    password: dspqmdemft
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 10
  jpa: 
    hibernate:
      ddl-auto: create or update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect